### ISSUE TITLE
[i] should display some info like it used to do before instead of linking to README only

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/mathbin#3]
I thought of adding at least common asciimath commands and maybe some other stuff to an [i] popup, and then a link to the readme. Something like this:

```
,---------------------------------------------. [i]
|        a                          dy        |
| a/b   ---         dy/dx          ----       |
|        b                          dx        |
|                                             |
| a//b  a/b         int f(x)\ dx   ∫ f(x) dx  |
|                                             |
| ...                       ...               |
|                                             |
|                                             |
|                                             |
| [Click here] for more info about MathPaste. |
`---------------------------------------------'
```

Then clicking the link would bring to the README. What do you think?

**Comment by PurpleMyst** [comment]
I'd be okay with this, especially since I've already written the code to handle opening a box with the info box. Would you be willing to write out the contents of this info box?

**Comment by Akuli** [comment]
Yes.

**Comment by PurpleMyst** [comment]
How would you prefer to go about this? Should I add an empty info box and you make a PR filling it out?

**Comment by Akuli** [comment]
that's ok

**Comment by Akuli** [comment]
#6 implements this
