### ISSUE TITLE
Sync up editor portion and display portion scroll bars.

### ISSUE THREAD

**Issue by PurpleMyst** [PurpleMyst/mathbin#4]
This feature has been requested on IRC by `xqb`, who does not have a GitHub account.

I am not sure on how to go about this, seeing as the relationship between the editor and display portion is not one-to-one, rather many-to-one. I'm pretty sure it is possible, however.

**Comment by Akuli** [comment]
How about highlighting the output line that corresponds to the line that the cursor is on (would be neat on its own too), and then making sure that the line is always scrolled to be visible in the output?

**Comment by Akuli** [comment]
this is implemented on my fork now: https://akuli.github.io/mathpaste/

@PurpleMyst, what should we do with your fork? Currently I'm using my own fork for everything anyway.

**Comment by Akuli** [comment]
Now myst's fork redirects to my fork
