### ISSUE TITLE
url shortener button

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/mathbin#5]
Mathpaste urls can get huge and they must be pasted manually to an url shortener. Can we add a button that does that and sends the result in a modal box?

**Comment by PurpleMyst** [comment]
That's a great idea. I just need to find some URL shortener service with a nice API.

**Comment by Akuli** [comment]
Can you tell github pages to use the `gh-pages` branch? I would like to start using this feature soon.

**Comment by Akuli** [comment]
this feature has been usable for a long time now
