### ISSUE TITLE
support for drawing stuff?

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/mathbin#7]
A picture can be worth a thousand words. Or something like that. I don't remember the saying.

Anyway, it's often useful to draw pics when working with math. For example, why is -2 bigger than -5? It's obvious if we put the numbers on a number line because "bigger than" means "to the right of":

```
     -5    -2   0 1 2
------o-----o---o-o-o----->
```

Ideally mathpaste would contain some kind of drawing area where I can draw simple things like number lines, but also more complicated things like graphs, geometric shapes and stuff.

**Comment by PurpleMyst** [comment]
This is an interesting idea. Perhaps a button which opens a little drawing area, splitting the right area in half horizontally, would be enough?

**Comment by Akuli** [comment]
Something like that would be nice, yes. Also, we can dump a lot of stuff on firebase, so storigin the pics somewhere shouldn't be a huge problem.

**Comment by PurpleMyst** [comment]
I'll work on this in a few days.

**Comment by Akuli** [comment]
i did this on my mathpaste fork: https://github.com/Akuli/mathpaste
